# Generated by Django 4.2.6 on 2023-10-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default='bhagya', max_length=200),
            preserve_default=False,
        ),
    ]
